---
title: "Rumex DFE plots"
author: "Meng"
date: "2023-05-17"
output: html_document
---

```{r setup, include=FALSE}
library(tidyr)
library(dplyr)
library(ggplot2)
library(patchwork)
library(RColorBrewer)
library("gridExtra")
knitr::opts_chunk$set(echo = TRUE)
directory="/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_haploid_sel/DFE/"

data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE),
      sem = sd(x[[col]], na.rm=TRUE) / sqrt(length(x[[col]])),
      lower <- quantile(x[[col]], 0.025),
      upper <- quantile(x[[col]], 0.975))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
 return(data_sum)
}
```


## bootstrapping data
```{r}
read_and_process_data <- function(directory, qt_number) {
  bs_pollen <- read.table(paste0(directory, "p_qt", qt_number, "_bs.prop_muts.txt"))
  bs_leaf <- read.table(paste0(directory, "l_qt", qt_number, "_bs.prop_muts.txt"))
  bs_u <- read.table(paste0(directory, "u_qt", qt_number, "_bs.prop_muts.txt"))
  
  bs_pollen$V5 <- rowSums(bs_pollen[, 3:4])
  bs_pollen <- bs_pollen[, c(1:2, 5)]
  colnames(bs_pollen) <- c("0~1", "1~10", ">10")

  bs_leaf$V5 <- rowSums(bs_leaf[, 3:4])
  bs_leaf <- bs_leaf[, c(1:2, 5)]
  colnames(bs_leaf) <- c("0~1", "1~10", ">10")

  bs_u$V5 <- rowSums(bs_u[, 3:4])
  bs_u <- bs_u[, c(1:2, 5)]
  colnames(bs_u) <- c("0~1", "1~10", ">10")

  bs_leaf$Category <- "sporophyte"
  bs_pollen$Category <- "gametophyte"
  bs_u$Category <- "unbiased"
  
  # Convert to long format
  pollen_long <- gather(bs_pollen, Nes, Prop, "0~1" : ">10", factor_key = TRUE)
  leaf_long <- gather(bs_leaf, Nes, Prop, "0~1" : ">10", factor_key = TRUE)
  u_long <- gather(bs_u, Nes, Prop, "0~1" : ">10", factor_key = TRUE)
  
  # get error bar
  bs_all <-rbind(pollen_long,leaf_long,u_long)
  summary <- data_summary(bs_all, varname="Prop", 
                    groupnames=c("Category", "Nes"))
  return(summary)
}

prop_qt_list <- list()

# Loop through the different quantiles
for (qt_number in 1:4) {
  prop_qt <- read_and_process_data(directory, qt_number)
  prop_qt$Quantile <- paste0("qt", qt_number)
  prop_qt_list[[qt_number]] <- prop_qt
}

dfr <- do.call(rbind, prop_qt_list)
colnames(dfr)[6:7] <- c("lower", "higher")
write.table(dfr, file = paste0(directory,"final_prop_qt_apr.txt"), row.names = F, quote = F)
```


## plot DFE, mean & CI
```{r}
dfr$Category <- factor(dfr$Category)
levels(dfr$Category)
dfr$Category <- factor(dfr$Category, level=c("sporophyte", "unbiased", "gametophyte"))
ggplot(dfr, aes(x=Nes,y=mean,fill=Category)) + geom_bar(stat="identity", position=position_dodge()) + theme_classic() + scale_x_discrete(limits=c("0~1", "1~10", ">10")) + scale_fill_manual(values = c("#CCEBC5", "#238B45","green"))  + labs(y="Proportion of mutations") + geom_errorbar(aes(ymin=lower, ymax=higher), width=.2, position=position_dodge(.9)) +ggtitle("b") + theme(text = element_text(size = 10))+
    facet_grid(.~Quantile,scales="free_x", switch = "x", space = "free_x") 
```
```{r}
dfr <- read.table("/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_haploid_sel/DFE/final_prop_qt_apr.txt", header=T)
dfr$Category <- factor(dfr$Category)
levels(dfr$Category)
dfr$Category <- factor(dfr$Category, level=c("sporophyte", "unbiased", "gametophyte"))

df <- read.table("/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/ceratodon_haploid_sel/DFE/final_prop_qt_apr.txt", header=T)
df$Category <- factor(df$Category)
levels(df$Category)
df$Category <- factor(df$Category, level=c("sporophyte", "unbiased", "gametophyte"))
```


```{r}
p1 <- ggplot(dfr, aes(x=Nes,y=mean,fill=Category)) + geom_bar(stat="identity", position=position_dodge()) + theme_classic() + scale_x_discrete(limits=c("0~1", "1~10", ">10")) + scale_fill_manual(values = c("#E6F5D0", "#B8E186", "#238B45"))  + labs(x=expression(italic(paste(N[e], "s"))), y="Proportion of mutations") + geom_errorbar(aes(ymin=lower, ymax=higher), width=.2, position=position_dodge(.9)) + ggtitle("a") + theme(text = element_text(size = 10))+
    facet_grid(.~Quantile,scales="free_x", switch = "x", space = "free_x") 

p2 <- ggplot(df, aes(x=Nes,y=mean,fill=Category)) + geom_bar(stat="identity", position=position_dodge()) + theme_classic() + scale_x_discrete(limits=c("0~1", "1~10", ">10")) + scale_fill_manual(values = c("#E6F5D0", "#B8E186", "#238B45"))  + labs(x=expression(italic(paste(N[e], "s"))), y="Proportion of mutations") + geom_errorbar(aes(ymin=lower, ymax=higher), width=.2, position=position_dodge(.9)) + ggtitle("b") + theme(text = element_text(size = 10))+
    facet_grid(.~Quantile,scales="free_x", switch = "x", space = "free_x") 

p1 + p2 + plot_layout(nrow = 2,guides = "collect") & theme(legend.position = "right")
```

# all quantiles combined/no quantiles
```{r}
directory="/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_haploid_sel/DFE/"
bs_g <- read.table(paste0(directory, "genesp_bs.prop_muts.txt"))
bs_s <- read.table(paste0(directory, "genesl_bs.prop_muts.txt"))
bs_u <- read.table(paste0(directory, "unbias_bs.prop_muts.txt"))

bs_g$V5 <- rowSums(bs_g[, 3:4])
bs_g <- bs_g[, c(1:2, 5)]
colnames(bs_g) <- c("0~1", "1~10", ">10")
bs_s$V5 <- rowSums(bs_s[, 3:4])
bs_s <- bs_s[, c(1:2, 5)]
colnames(bs_s) <- c("0~1", "1~10", ">10")
bs_u$V5 <- rowSums(bs_u[, 3:4])
bs_u <- bs_u[, c(1:2, 5)]
colnames(bs_u) <- c("0~1", "1~10", ">10")

bs_s$Category <- "sporophyte"
bs_g$Category <- "gametophyte"
bs_u$Category <- "unbiased"
  
# Convert to long format
g_long <- gather(bs_g, Nes, Prop, "0~1" : ">10", factor_key = TRUE)
s_long <- gather(bs_s, Nes, Prop, "0~1" : ">10", factor_key = TRUE)
u_long <- gather(bs_u, Nes, Prop, "0~1" : ">10", factor_key = TRUE)

# get error bar
bs_all <-rbind(g_long,s_long,u_long)
dfr2 <- data_summary(bs_all, varname="Prop", 
                    groupnames=c("Category", "Nes"))
colnames(dfr2)[6:7] <- c("lower", "higher")
write.table(dfr2, file = paste0(directory,"final_prop_apr.txt"), row.names = F, quote = F,sep = "\t")
```

```{r}
dfr2 <- read.table("/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_haploid_sel/DFE/final_prop_apr.txt", header=T)
dfr2$Category <- factor(dfr2$Category)
levels(dfr2$Category)
dfr2$Category <- factor(dfr2$Category, level=c("sporophyte", "unbiased", "gametophyte"))

df2 <- read.table("/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/ceratodon_haploid_sel/DFE/final_prop_apr.txt", header=T)
df2$Category <- factor(df2$Category)
levels(df2$Category)
df2$Category <- factor(df2$Category, level=c("sporophyte", "unbiased", "gametophyte"))
```


```{r}
p3 <- ggplot(dfr2, aes(x=Nes,y=mean,fill=Category)) + geom_bar(stat="identity", position=position_dodge()) + theme_classic() + scale_x_discrete(limits=c("0~1", "1~10", ">10")) + scale_fill_manual(values = c("#E6F5D0", "#B8E186", "#238B45")) + labs(x=expression(italic(paste(N[e], "s"))), y="Proportion of mutations") + geom_errorbar(aes(ymin=lower, ymax=higher), width=.2, position=position_dodge(.9)) +ggtitle("a") + theme(text = element_text(size = 10))

p4 <- ggplot(df2, aes(x=Nes,y=mean,fill=Category)) + geom_bar(stat="identity", position=position_dodge()) + theme_classic() + scale_x_discrete(limits=c("0~1", "1~10", ">10")) + scale_fill_manual(values = c("#E6F5D0", "#B8E186", "#238B45")) + labs(x=expression(italic(paste(N[e], "s"))), y="Proportion of mutations") + geom_errorbar(aes(ymin=lower, ymax=higher), width=.2, position=position_dodge(.9)) +ggtitle("b") + theme(text = element_text(size = 10))

p3 + p4 + plot_layout(guides = "collect") & theme(legend.position = "right")
```

 