---
title: "FC - pi plot"
author: "Meng"
date: "2023-06-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(rattle)
directory="/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_haploid_sel/pixy/"
```
## merge with pi data
```{r}
pixy <- read.csv(paste0(directory,"pixy_LG_clean.csv"), header=TRUE) 
colnames(pixy)[8] <- "gene"
FC_pixy<- inner_join(DE_tissue,pixy,by=c("gene")) # 24352
write.csv(FC_pixy, file = paste0(directory,"FC_pixy_innerjoin.csv"), row.names = FALSE, quote = FALSE)
FC_pixy <- FC_pixy %>% filter(no_sites>10)
mean(FC_pixy$no_sites)
```
mean(FC_pixy$no_sites) 100
no_sites>10 for now: 24253 -> 23163


## prepare gene sets
separate to p-biased and l-biased
then 4 quantiles within each category
DE gene cutoffs: padj<0.1 & baseMean >= 1
logFC>0: pollen biased, logFC <-: leaf biased
```{r}
# DE_tissue <- read.csv("/Users/yuanmeng/Dropbox/Rumex_eQTL/plot/DE_tissue.csv")
pollen_bias <- FC_pixy %>% filter(log2FoldChange>0) # 23064 -> 11262
leaf_bias <- FC_pixy %>% filter(log2FoldChange<0) # 14813 -> 11901

bin<-binning(pollen_bias$log2FoldChange, bins=4, method="quantile",
                     labels=NULL, ordered=TRUE, weights=NULL)
plot(bin)

bin<-binning(leaf_bias$log2FoldChange, bins=4, method="quantile",
                     labels=NULL, ordered=TRUE, weights=NULL)
plot(bin)
```
document how many genes in each bin
pollen
[0.000689, 1.24]
(1.24,2.37]
(2.37, 4.28]
(4.28, 29.6]

leaf
[-7.46, -2.89]
(-2.89,-1.96]
(-1.96,-1.08]
(-1.08, -8.57e-5]


>bootstrap for pi in each bin? (no gene-by-gene stats)

break and tags for FC
```{r}
breaks <- c(0,0.00102,0.117,0.224,0.4,0.802,1.82,5.21,27.8)
# specify interval/bin labels
tags <- c("[0-0.239)","[0.239-0.486)", "[0.486-0.705)", "[0.705-0.95)", "[0.95-1.25)", "[1.25-1.8)","[1.8-3.7)", "[3.7-inf)")

# bucketing values into bins
group_tags <- cut(FC_pixy$log2FoldChange, 
                  breaks=breaks, 
                  include.lowest=TRUE, 
                  right=FALSE, 
                  labels=tags)
# inspect bins
summary(group_tags)

ratio_groups <- factor(group_tags, 
                           levels = tags,
                           ordered = TRUE)
```
pollen
[0.000689, 1.24]
(1.24,2.37]
(2.37, 4.28]
(4.28, 29.6]

leaf
[-7.46, -2.89]
(-2.89,-1.96]
(-1.96,-1.08]
(-1.08, -8.57e-5]

## plot
```{r}
v <- FC_pixy %>% select(log2FoldChange,avg_pi) 
vgroup <- as_tibble(v) %>% 
  mutate(tag = case_when(
    log2FoldChange > 0 & log2FoldChange <= 1.24 ~ tags[5],
    log2FoldChange > 1.24 & log2FoldChange <= 2.37 ~ tags[6],
    log2FoldChange > 2.37 & log2FoldChange <= 4.28 ~ tags[7],
    log2FoldChange > 4.28 & log2FoldChange <= 29.6 ~ tags[8],
    
    log2FoldChange >= -7.46 & log2FoldChange <= -2.89 ~ tags[1],
    log2FoldChange > -2.89 & log2FoldChange <= -1.96 ~ tags[2],
    log2FoldChange > -1.96 & log2FoldChange <= -1.08 ~ tags[3],
    log2FoldChange > -1.08 & log2FoldChange < 0 ~ tags[4]

    ))
summary(vgroup)

vgroup$tag <- factor(vgroup$tag,
                       levels = tags,
                       ordered = FALSE)

ggplot(data = vgroup, mapping = aes(x=tag,y=avg_pi)) + 
  geom_jitter(aes(color='blue'),alpha=0.2) +
  geom_boxplot(fill="bisque",color="black",alpha=0.3) + 
  labs(x='pollen_leaf_ratio') +
  guides(color=FALSE) + ylim(0,0.2) +
  theme_minimal() 
```






