---
title: "FC and pi linear graphs"
author: "Meng"
date: "2024-04-09"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(patchwork)
```

# rumex
## pi - log2FC regression 
 do piS original piN and  remove zero for ratio
```{r}
directory="/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_haploid_sel/pixy/"
statsr <- read.csv(paste0(directory,"rumex_pi_n_pi_s.csv"))

p1 <- ggplot(statsr, aes(x=log2FoldChange, y=avg_pi)) + geom_point(colour="#1F78B4", alpha=0.2) + geom_smooth(color="black", method = lm) + theme_classic() + theme(text = element_text(size = 10))+ labs(x='log2FoldChange', y=expression(pi[s])) + ggtitle('a')

p2 <- ggplot(statsr, aes(x=abs(log2FoldChange), y=avg_pi)) + geom_point(colour="#1F78B4", alpha=0.2) + geom_smooth(color="black", method = lm) + theme_classic() + theme(text = element_text(size = 10))+ labs(x='abs(log2FoldChange)', y=expression(pi[s])) + ggtitle('d')


p3 <- ggplot(statsr, aes(x=log2FoldChange, y=avg_pi_nonsyn)) + geom_point(colour="#1F78B4", alpha=0.2) + geom_smooth(color="black", method = lm) + theme_classic() + theme(text = element_text(size = 10))+ labs(x='log2FoldChange', y=expression(pi[n])) + ggtitle('b')

p4 <- ggplot(statsr, aes(x=abs(log2FoldChange), y=avg_pi_nonsyn)) + geom_point(colour="#1F78B4", alpha=0.2) + geom_smooth(color="black", method = lm) + theme_classic() + theme(text = element_text(size = 10))+ labs(x='abs(log2FoldChange)', y=expression(pi[n])) + ggtitle('e')

statsr <- statsr %>% filter(avg_pi != 0 & avg_pi_nonsyn  != 0)
statsr$pi_ratio <- statsr$avg_pi_nonsyn / statsr$avg_pi

p5 <- ggplot(statsr, aes(x=log2FoldChange, y=pi_ratio)) + geom_point(colour="#1F78B4", alpha=0.2) + geom_smooth(color="black", method = lm) + theme_classic() + theme(text = element_text(size = 10))+ labs(x='log2FoldChange', y=expression(paste(pi[n], "/", pi[s], " ratio"))) + ggtitle('c')

p6 <- ggplot(statsr, aes(x=abs(log2FoldChange), y=pi_ratio)) + geom_point(colour="#1F78B4", alpha=0.2) + geom_smooth(color="black", method = lm) + theme_classic() + theme(text = element_text(size = 10))+ labs(x='abs(log2FoldChange)', y=expression(paste(pi[n], "/", pi[s], " ratio"))) + ggtitle('f')

p1 + p2 + p3 + p4 + p5 + p6 + plot_layout(nrow = 3)
```

linear regression
```{r}
#cor(FC_pixy$avg_pi, FC_pixy$log2FoldChange) # 0.04935226
#cor(FC_pixy$avg_pi, abs(FC_pixy$log2FoldChange)) # 0.06233079

model <- lm(avg_pi ~ log2FoldChange, data = statsr)
summary(model)
model <- lm(avg_pi ~ abs(log2FoldChange), data = statsr)
summary(model)
model <- lm(avg_pi_nonsyn ~ log2FoldChange, data = statsr)
summary(model)
model <- lm(avg_pi_nonsyn ~ abs(log2FoldChange), data = statsr)
summary(model)

statsr <- statsr %>% filter(avg_pi != 0 & avg_pi_nonsyn  != 0)
statsr$pi_ratio <- statsr$avg_pi_nonsyn / statsr$avg_pi
model <- lm(pi_ratio ~ log2FoldChange, data = statsr)
summary(model)
model <- lm(pi_ratio ~ abs(log2FoldChange), data = statsr)
summary(model)
```


# ceratodon
## pi - log2FC regression 
```{r}
directory="/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/ceratodon_haploid_sel/diversity/"
stats  <- read.csv(paste0(directory,"ceratodon_pi_n_pi_s.csv"))

p1 <- ggplot(stats, aes(x=log2FoldChange, y=avg_pi)) + geom_point(colour="#1F78B4", alpha=0.2) + geom_smooth(color="black", method = lm) + theme_classic() + theme(text = element_text(size = 10))+ labs(x='log2FoldChange', y=expression(pi[s])) + ggtitle('a')

p2 <- ggplot(stats, aes(x=abs(log2FoldChange), y=avg_pi)) + geom_point(colour="#1F78B4", alpha=0.2) + geom_smooth(color="black", method = lm) + theme_classic() + theme(text = element_text(size = 10))+ labs(x='abs(log2FoldChange)', y=expression(pi[s])) + ggtitle('d')


p3 <- ggplot(stats, aes(x=log2FoldChange, y=avg_pi_nonsyn)) + geom_point(colour="#1F78B4", alpha=0.2) + geom_smooth(color="black", method = lm) + theme_classic() + theme(text = element_text(size = 10))+ labs(x='log2FoldChange', y=expression(pi[n])) + ggtitle('b')

p4 <- ggplot(stats, aes(x=abs(log2FoldChange), y=avg_pi_nonsyn)) + geom_point(colour="#1F78B4", alpha=0.2) + geom_smooth(color="black", method = lm) + theme_classic() + theme(text = element_text(size = 10))+ labs(x='abs(log2FoldChange)', y=expression(pi[n])) + ggtitle('e')

stats <- stats %>% filter(avg_pi != 0 & avg_pi_nonsyn  != 0)
stats$pi_ratio <- stats$avg_pi_nonsyn / stats$avg_pi

p5 <- ggplot(stats, aes(x=log2FoldChange, y=pi_ratio)) + geom_point(colour="#1F78B4", alpha=0.2) + geom_smooth(color="black", method = lm) + theme_classic() + theme(text = element_text(size = 10))+ labs(x='log2FoldChange', y=expression(paste(pi[n], "/", pi[s], " ratio"))) + ggtitle('c')

p6 <- ggplot(stats, aes(x=abs(log2FoldChange), y=pi_ratio)) + geom_point(colour="#1F78B4", alpha=0.2) + geom_smooth(color="black", method = lm) + theme_classic() + theme(text = element_text(size = 10))+ labs(x='abs(log2FoldChange)', y=expression(paste(pi[n], "/", pi[s], " ratio"))) + ggtitle('f')

p1 + p2 + p3 + p4 + p5 + p6 + plot_layout(nrow = 3)
```

linear regression
```{r}
model <- lm(avg_pi ~ log2FoldChange, data = stats)
summary(model)
model <- lm(avg_pi ~ abs(log2FoldChange), data = stats)
summary(model)
model <- lm(avg_pi_nonsyn ~ log2FoldChange, data = stats)
summary(model)
model <- lm(avg_pi_nonsyn ~ abs(log2FoldChange), data = stats)
summary(model)

stats <- stats %>% filter(avg_pi != 0 & avg_pi_nonsyn  != 0)
stats$pi_ratio <- stats$avg_pi_nonsyn / stats$avg_pi
model <- lm(pi_ratio ~ log2FoldChange, data = stats)
summary(model)
model <- lm(pi_ratio ~ abs(log2FoldChange), data = stats)
summary(model)
```
