---
title: "FC and tajD rumex"
author: "Meng"
date: "2023-12-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(patchwork)
library(dplyr)
library(ggplot2)
directory="/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_haploid_sel/pixy/"
```

## merge tajD estimates
```{r}
tajD <- read.csv(paste0(directory,"rumex_tajD.filt0329_syn.csv")) # 26967
tajD <- read.csv(paste0(directory,"rumex_tajD.filt0329_nonsyn.csv")) # 26967

tajD <- tajD[complete.cases(tajD),] # 17026 19771 (nonsyn)
colnames(tajD)[1] <- "chrom"
    
DE_tissue <- read.table("/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_haploid_sel/deseq2/result_tissue_full.txt", header=T)
DE_tissue <- DE_tissue %>% filter(p_mean>5 | l_mean>5)  # 17982

FC_tajD<- inner_join(DE_tissue, tajD, by=c("chrom","start","end")) # 10863
FC_tajD_n<- inner_join(DE_tissue, tajD, by=c("chrom","start","end")) # 12658

write.table(FC_tajD, file = paste0(directory,"FC_tajD_syn_innerjoin.txt"), row.names = FALSE, quote = FALSE)
write.table(FC_tajD_n, file = paste0(directory,"FC_tajD_nonsyn_innerjoin.txt"), row.names = FALSE, quote = FALSE)

FC_tajD <- read.table(paste0(directory,"FC_tajD_syn_innerjoin.txt"), header =T)
FC_tajD_n <- read.table(paste0(directory,"FC_tajD_nonsyn_innerjoin.txt"), header =T)
```


## separate data into FC bin
```{r}
tags <- c("s4", "s3", "s2", "s1", "g1", "g2", "g3", "g4")
FC_tajD <- as_tibble(FC_tajD) %>% 
  mutate(tag = case_when(
    log2FoldChange > 0 & log2FoldChange <= 1.143 ~ tags[5],
    log2FoldChange > 1.143 & log2FoldChange <= 2.79 ~ tags[6],
    log2FoldChange > 2.79 & log2FoldChange <= 5.7235 ~ tags[7],
    log2FoldChange > 5.7235   ~ tags[8],
    
    log2FoldChange <= -3.0162 ~ tags[1],
    log2FoldChange > -3.0162 & log2FoldChange <= -2.154298 ~ tags[2],
    log2FoldChange > -2.154298 & log2FoldChange <= -1.255 ~ tags[3],
    log2FoldChange > -1.255 & log2FoldChange < 0 ~ tags[4]
    ))
table(FC_tajD$tag)

FC_tajD_n <- as_tibble(FC_tajD_n) %>% 
  mutate(tag = case_when(
    log2FoldChange > 0 & log2FoldChange <= 1.143 ~ tags[5],
    log2FoldChange > 1.143 & log2FoldChange <= 2.79 ~ tags[6],
    log2FoldChange > 2.79 & log2FoldChange <= 5.7235 ~ tags[7],
    log2FoldChange > 5.7235   ~ tags[8],
    
    log2FoldChange <= -3.0162 ~ tags[1],
    log2FoldChange > -3.0162 & log2FoldChange <= -2.154298 ~ tags[2],
    log2FoldChange > -2.154298 & log2FoldChange <= -1.255 ~ tags[3],
    log2FoldChange > -1.255 & log2FoldChange < 0 ~ tags[4]
    ))
table(FC_tajD_n$tag)

```
  g1   g2   g3   g4   s1   s2   s3   s4 
1096 1052 1063 1009 1616 1632 1661 1734 

  g1   g2   g3   g4   s1   s2   s3   s4 
1296 1255 1231 1197 1872 1904 1937 1966

## Taj D within each bin

```{r}
tags <- c("(,-3.02]","(-3.02,-2.16]", "(-2.16,-1.27]", "(-1.27,0)", "(0,1.02]", "(1.02,2.54]","(2.54,5.36]", "(5.36,)")
FC_tajD <- as_tibble(FC_tajD) %>% 
  mutate(tag = case_when(
    log2FoldChange > 0 & log2FoldChange <= 1.02 ~ tags[5],
    log2FoldChange > 1.02 & log2FoldChange <= 2.54 ~ tags[6],
    log2FoldChange > 2.54 & log2FoldChange <= 5.36 ~ tags[7],
    log2FoldChange > 5.36   ~ tags[8],
    
    log2FoldChange <= -3.02 ~ tags[1],
    log2FoldChange > -3.02 & log2FoldChange <= -2.16 ~ tags[2],
    log2FoldChange > -2.16 & log2FoldChange <= -1.27 ~ tags[3],
    log2FoldChange > -1.27 & log2FoldChange < 0 ~ tags[4]
    ))
table(FC_tajD$tag)

FC_tajD_n <- as_tibble(FC_tajD_n) %>% 
  mutate(tag = case_when(
    log2FoldChange > 0 & log2FoldChange <= 1.02 ~ tags[5],
    log2FoldChange > 1.02 & log2FoldChange <= 2.54 ~ tags[6],
    log2FoldChange > 2.54 & log2FoldChange <= 5.36 ~ tags[7],
    log2FoldChange > 5.36   ~ tags[8],
    
    log2FoldChange <= -3.02 ~ tags[1],
    log2FoldChange > -3.02 & log2FoldChange <= -2.16 ~ tags[2],
    log2FoldChange > -2.16 & log2FoldChange <= -1.27 ~ tags[3],
    log2FoldChange > -1.27 & log2FoldChange < 0 ~ tags[4]
    ))
table(FC_tajD_n$tag)
```
(-1.27,0) (-2.16,-1.27] (-3.02,-2.16]      (,-3.02]      (0,1.02]   (1.02,2.54] 
         1633          1627          1653          1730           986          1044 
  (2.54,5.36]       (5.36,) 
         1078          1112 

   (-1.27,0) (-2.16,-1.27] (-3.02,-2.16]      (,-3.02]      (0,1.02]   (1.02,2.54] 
         1894          1895          1931          1959          1167          1238 
  (2.54,5.36]       (5.36,) 
         1264          1310 
         

## get mean & sem
```{r}
mean_tajD <- FC_tajD %>% group_by(tag) %>%
  dplyr::summarise(
    count = length(TajD_TX),
    mean_tajD = mean(TajD_TX),
    sem_tajD = sd(TajD_TX)/sqrt(length(TajD_TX))
  )

mean_tajD_n <- FC_tajD_n %>% group_by(tag) %>%
  dplyr::summarise(
    count = length(TajD_TX),
    mean_tajD = mean(TajD_TX),
    sem_tajD = sd(TajD_TX)/sqrt(length(TajD_TX))
  )

mean_tajD <- mean_tajD %>% mutate(tag = factor(tag, levels = c("s4", "s3", "s2", "s1", "g1", "g2", "g3", "g4")))
levels(mean_tajD$tag)

mean_tajD_n <- mean_tajD_n %>% mutate(tag = factor(tag, levels = c("s4", "s3", "s2", "s1", "g1", "g2", "g3", "g4")))
levels(mean_tajD_n$tag)
```


## plot the output
```{r}
p1 <- ggplot(data = mean_tajD, mapping = aes(x=tag, y=mean_tajD)) + 
    geom_point()+ geom_errorbar(aes(ymin=mean_tajD - sem_tajD, ymax=mean_tajD + sem_tajD), width=.2, position=position_dodge(.9))+ ggtitle("a") +labs(x ="log2FoldChange",y = expression(D[s]))+ theme_classic()+ theme(text = element_text(size = 10), axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank())

p2 <- ggplot(data = mean_tajD_n, mapping = aes(x=tag, y=mean_tajD)) + 
    geom_point()+ geom_errorbar(aes(ymin=mean_tajD - sem_tajD, ymax=mean_tajD + sem_tajD), width=.2, position=position_dodge(.9))+ ggtitle("b") +labs(x ="log2FoldChange",y = expression(D[n]))+ theme_classic() + theme(text = element_text(size = 10), axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank()) 

p1 + p2
```

```{r}
(p1 | p3) / (p2 | p4) 
```


## write output
```{r}
directory="/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_haploid_sel/pixy/"
write.table(mean_tajD, file = paste0(directory,"mean_tajD_s_apr.txt"), row.names = FALSE, quote = FALSE)
write.table(mean_tajD_n, file = paste0(directory,"mean_tajD_n_apr.txt"), row.names = FALSE, quote = FALSE)
mean_tajD <- read.table(paste0(directory,"mean_tajD_s_apr.txt"), header = T)
mean_tajD_n <- read.table(paste0(directory,"mean_tajD_n_apr.txt"), header = T)

```

