---
title: "expression ratio and diversity"
author: "Meng"
date: "2023-05-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
directory="/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_haploid_sel/pixy/"
library(dplyr)
```


## read stats (eg. pi)
```{r}
pixy <- read.table(paste0(directory,"pixy_pi_syn.0329.genewise.txt"), header=TRUE) 
pixy <- pixy %>% filter(no_sites>=50) # 19542
colnames(pixy)[2:4] <- c("chrom", "start", "end")
pixy <- inner_join(pixy, gff, by=c("chrom", "start", "end")) # 15049
write.table(pixy, file = paste0(directory,"pixy_filtered.txt"), quote=F) # 14282

cnt <- cnt %>% filter(mean>0) # 27154
ratio_pixy<- inner_join(cnt,pixy,by="gene") # 14282
write.table(ratio_pixy, file = paste0(directory,"ratio_pixy.txt"), row.names = FALSE, quote = FALSE)
```

change pollen_leaf_ratio inf to one category, 0 to another category
change inf to 30000000
```{r}
# get a subset for binning quantiles
ratio_pixy2<- ratio_pixy %>% filter(p_l_ratio>0)  %>% filter(is.finite(p_l_ratio)) # 13470
#ratio_pixy[which(!is.finite(ratio_pixy$pollen_leaf_ratio)),] <- 10000000
#ratio_pixy <- do.call(data.frame, lapply(ratio_pixy,function(x) replace(x, is.infinite(x), 10000000)))
```

pollen/leaf  
0=leaf specific, inf=pollen specific

```{r}
ggplot(ratio_pixy, aes(x=log10(pollen_leaf_ratio), y=avg_pi)) + geom_point(colour="#00B0F0") + geom_smooth(color="black") + theme_light() + xlim(-2, 2)
```


## plot

```{r}
ratio_pixy_l <- ratio_pixy2 %>% filter(p_l_ratio<1)
ratio_pixy_p <- ratio_pixy2 %>% filter(p_l_ratio>1)

bin<-binning(ratio_pixy_l$p_l_ratio, bins=4, method="quantile",
                     labels=NULL, ordered=TRUE, weights=NULL)
bin<-binning(ratio_pixy_p$p_l_ratio, bins=4, method="quantile",
                     labels=NULL, ordered=TRUE, weights=NULL)
plot(bin)
ratio_pixy2 <- ratio_pixy2[complete.cases(ratio_pixy2),]
ratio_pixy <- ratio_pixy[complete.cases(ratio_pixy),]
# set up cut-off values 
breaks <- c(-1, 0,0.00102,0.117,0.224,0.4,0.802,1.82,5.21,27.8,300000000000,100000000000000)
# specify interval/bin labels
tags <- c("0","[0-0.239)","[0.239-0.486)", "[0.486-0.705)", "[0.705-0.95)", "[0.95-1.25)", "[1.25-1.8)","[1.8-3.7)", "[3.7-inf)","inf")

# bucketing values into bins
group_tags <- cut(ratio_pixy$pollen_leaf_ratio, 
                  breaks=breaks, 
                  include.lowest=TRUE, 
                  right=FALSE, 
                  labels=tags)
# inspect bins
summary(group_tags)
ratio_groups <- factor(group_tags, 
                           levels = tags,
                           ordered = TRUE)

# the real graph 0,0.00102,0.117,0.224,0.4,0.802,1.82,5.21,27.8
v <- ratio_pixy %>% select(p_l_ratio,avg_pi) #pick the variable 
vgroup <- as_tibble(v) %>% 
  mutate(tag = case_when(
    p_l_ratio == 0 ~ tags[1], 
    p_l_ratio > 0 & p_l_ratio <= 0.12 ~ tags[2],
    p_l_ratio > 0.12 & p_l_ratio <= 0.225 ~ tags[3],
    p_l_ratio > 0.225 & p_l_ratio <= 0.429 ~ tags[4],
    p_l_ratio > 0.429 & p_l_ratio <= 1 ~ tags[5],
    p_l_ratio > 1 & p_l_ratio <= 1.97 ~ tags[6],
    p_l_ratio > 1.97 & p_l_ratio <= 5.11 ~ tags[7],
    p_l_ratio > 5.11 & p_l_ratio <= 28.3 ~ tags[8],
    p_l_ratio > 28.3  ~ tags[9],
    is.infinite(p_l_ratio) == TRUE ~ tags[10]
    ))
#summary(vgroup)

vgroup$tag <- factor(vgroup$tag,
                       levels = tags,
                       ordered = FALSE)

ggplot(data = vgroup, mapping = aes(x=tag,y=avg_pi)) + 
  geom_jitter(aes(color='blue'),alpha=0.2) +
  geom_boxplot(fill="bisque",color="black",alpha=0.3) + 
  labs(x='pollen_leaf_ratio') +
  guides(color=FALSE) + ylim(0,0.06) +
  theme_minimal() 

ggplot(data = vgroup, mapping = aes(x=tag,y=avg_pi)) + 
    geom_jitter(color="#1F78B4",alpha=0.2) +
    geom_boxplot(fill="#1F78B4",color="black",alpha=0.3) + 
    labs(x='g_s_ratio') +
    guides(color=FALSE) + ylim(0,0.06)+
    theme_classic() + theme(text = element_text(size = 18))

```
0.12]
0.225]
0.429]
(
[1, 1.97]
5.11]
28.3]
(
