---
title: "specific vs unbiased genes and pi"
author: "Meng"
date: "2024-04-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(patchwork)
library(dplyr)
library(ggplot2)
```

# functions
## bootstrap mean and CI
```{r}
# a function to calculate the weighted average of pi_n pi_s
calculate_pi <- function(data) {
    data <- data %>%
      mutate(pi_syn = avg_pi * no_sites.x) %>%
      mutate(pi_nonsyn = avg_pi_nonsyn * no_sites.y)
    sum_pi_syn <- sum(data$pi_syn)
    sum_pi_nonsyn <- sum(data$pi_nonsyn)
    sum_no_sites_x <- sum(data$no_sites.x)
    sum_no_sites_y <- sum(data$no_sites.y)
    weighted_pi_syn <- sum_pi_syn / sum_no_sites_x
    weighted_pi_nonsyn <- sum_pi_nonsyn / sum_no_sites_y
    ratio_weighted_pis <- weighted_pi_nonsyn / weighted_pi_syn
    result <- data.frame(
      weighted_pi_syn = weighted_pi_syn,
      weighted_pi_nonsyn = weighted_pi_nonsyn,
      ratio_weighted_pis = ratio_weighted_pis
    )
    return(result)
  }
  
# bootstrap and calculate the mean and 95% of weighted average of pi_n pi_s pi_n/pi_s
bootstrap_calculate_pi <- function(data, iterations = 1000) {
    # set up the output format
    results <- data.frame(weighted_pi_syn = numeric(), weighted_pi_nonsyn = numeric(),   ratio_weighted_pis = numeric(), stringsAsFactors = FALSE)
    
    # bootstrap 1000 times and save to result
    for (i in 1:iterations) {
      resampled_data <- data[sample(nrow(data), replace = TRUE), ]
      calculated_values <- calculate_pi(resampled_data)
      if (nrow(results) == 0) {
        results <- calculated_values
      } else {
        results <- rbind(results, calculated_values)}
    }

    # calculate the mean and 95% CI from bootstrapped values
    output <- data.frame(
            mean_pi_syn = mean(results$weighted_pi_syn),
            mean_pi_nonsyn = mean(results$weighted_pi_nonsyn),
            mean_ratio_pis = mean(results$ratio_weighted_pis),
            lower_pi_syn = quantile(results$weighted_pi_syn, 0.025),
            higher_pi_syn = quantile(results$weighted_pi_syn, 0.975),
            lower_pi_nonsyn = quantile(results$weighted_pi_nonsyn, 0.025),
            higher_pi_nonsyn = quantile(results$weighted_pi_nonsyn, 0.975),
            lower_ratio_pis = quantile(results$ratio_weighted_pis, 0.025),
            higher_ratio_pis = quantile(results$ratio_weighted_pis, 0.975)
    )
    return(output)
  }
```

## mean and sem
```{r}
calculate_pi_real <- function(data) {
    data <- data %>%
      mutate(pi_syn = avg_pi * no_sites.x) %>%
      mutate(pi_nonsyn = avg_pi_nonsyn * no_sites.y) #%>%
      #mutate(ratio_pis = avg_pi_nonsyn / avg_pi) # issue with division by zero
    sum_pi_syn <- sum(data$pi_syn)
    sum_pi_nonsyn <- sum(data$pi_nonsyn)
    sum_no_sites_x <- sum(data$no_sites.x)
    sum_no_sites_y <- sum(data$no_sites.y)
    
    weighted_pi_syn <- sum_pi_syn / sum_no_sites_x
    weighted_pi_nonsyn <- sum_pi_nonsyn / sum_no_sites_y
    ratio_weighted_pis <- weighted_pi_nonsyn / weighted_pi_syn
    
    mean_avg_pi_syn <- mean(data$avg_pi)
    mean_avg_pi_nonsyn <- mean(data$avg_pi_nonsyn)
    #mean_ratio_pis <- mean(data$ratio_pis)
    
    sem_avg_pi_syn <- sd(data$avg_pi) / sqrt(length(data$avg_pi))
    sem_avg_pi_nonsyn <- sd(data$avg_pi_nonsyn) / sqrt(length(data$avg_pi_nonsyn))
    #sem_ratio_pis <- sd(data$ratio_pis) / sqrt(length(data$ratio_pis))
  
    result <- data.frame(
      count = length(data$tag),
      weighted_pi_syn = weighted_pi_syn,
      weighted_pi_nonsyn = weighted_pi_nonsyn,
      ratio_weighted_pis = ratio_weighted_pis,
      mean_avg_pi_syn =  mean_avg_pi_syn,
      mean_avg_pi_nonsyn = mean_avg_pi_nonsyn,
      #mean_ratio_pis = mean_ratio_pis,
      sem_avg_pi_syn = sem_avg_pi_syn,
      sem_avg_pi_nonsyn = sem_avg_pi_nonsyn
      #sem_ratio_pis = sem_ratio_pis
    )
    return(result)
}
```



# ceratodon
## gene sets in ceratodon
```{r}
directory="/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/ceratodon_haploid_sel/deseq2/"
geness_a <- read.table(paste0(directory,"geness_a.txt"), header = T)
genesg_a <- read.table(paste0(directory,"genesg_a.txt"), header = T)
unbiased <- read.table(paste0(directory,"unbiased.txt"), header = T)
```

## stats
```{r}
directory="/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/ceratodon_haploid_sel/diversity/"
stats  <- read.csv(paste0(directory,"ceratodon_pi_n_pi_s.csv"))

geness_a <- geness_a %>% dplyr::select(1)
genesg_a <- genesg_a %>% dplyr::select(1)
unbiased <- unbiased %>% dplyr::select(1)
stats_genesg_a <- inner_join(genesg_a, stats, by="gene") # 1217
stats_geness_a <- inner_join(geness_a, stats, by="gene") # 1232
stats_unbiased <- inner_join(unbiased, stats, by="gene") # 3747
```

## bootstrap mean & CI 
```{r}
pi_genesg_a <- bootstrap_calculate_pi(stats_genesg_a)
pi_genesg_a$category <- "gametophyte" 
    
pi_geness_a <- bootstrap_calculate_pi(stats_geness_a)
pi_geness_a$category <- "sporophyte" 

pi_unbiased_c <- bootstrap_calculate_pi(stats_unbiased)
pi_unbiased_c$category <- "unbiased" 

pi_genes_c <- rbind(pi_genesg_a, pi_geness_a, pi_unbiased_c)
directory="/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/ceratodon_haploid_sel/diversity/"
write.table(pi_genes_c, file = paste0(directory,"specific_genes_pi_apr.txt"), row.names = FALSE, sep = "\t", quote = FALSE)

pi_genes_c$category <- factor(pi_genes_c$category)
levels(pi_genes_c$category) 
pi_genes_c$category <- factor(pi_genes_c$category,
                       levels = c("sporophyte", "unbiased","gametophyte"))
```

## plot bs mean & CI
```{r}
p4 <- ggplot(data = pi_genes_c, mapping = aes(x=category, y=mean_pi_syn)) + 
    geom_point()+ geom_errorbar(aes(ymin=lower_pi_syn, ymax=higher_pi_syn), width=.2, position=position_dodge(.9))+ ggtitle("d") +labs(y = expression(pi[s]))+ theme_classic() + theme(text = element_text(size = 10),axis.title.x=element_blank())

p5 <- ggplot(data = pi_genes_c, mapping = aes(x=category, y=mean_pi_nonsyn)) + 
    geom_point()+ geom_errorbar(aes(ymin=lower_pi_nonsyn, ymax=higher_pi_nonsyn), width=.2, position=position_dodge(.9))+ ggtitle("e") +labs(y = expression(pi[n]))+ theme_classic() + theme(text = element_text(size = 10),axis.title.x=element_blank())

p6 <- ggplot(data = pi_genes_c, mapping = aes(x=category, y=mean_ratio_pis)) + 
    geom_point()+ geom_errorbar(aes(ymin=lower_ratio_pis, ymax=higher_ratio_pis), width=.2, position=position_dodge(.9))+ ggtitle("f") +labs(y = expression(paste(pi[n], "/", pi[s], " ratio")))+ theme_classic() + theme(text = element_text(size = 10),axis.title.x=element_blank())

p4 + p5 + p6 + plot_layout(nrow = 3,guides = "collect") 
```

## mean & sem
```{r}
pi_genesg_a <- calculate_pi_real(stats_genesg_a)
pi_genesg_a$category <- "gametophyte" 
    
pi_geness_a <- calculate_pi_real(stats_geness_a)
pi_geness_a$category <- "sporophyte" 

pi_unbiased <- calculate_pi_real(stats_unbiased)
pi_unbiased$category <- "unbiased" 

pi_genes_c_real <- rbind(pi_genesg_a, pi_geness_a, pi_unbiased)
directory="/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/ceratodon_haploid_sel/diversity/"
write.table(pi_genes_c_real, file = paste0(directory,"specific_genes_pi_real.txt"), row.names = FALSE, sep = "\t", quote = FALSE)

pi_genes_c_real$category <- factor(pi_genes_c_real$category)
levels(pi_genes_c_real$category) 
pi_genes_c_real$category <- factor(pi_genes_c_real$category,
                       levels = c("sporophyte", "unbiased","gametophyte"))
```

```{r}
p4_2 <- ggplot(data = pi_genes_c_real, mapping = aes(x=category, y=mean_avg_pi_syn)) + 
    geom_point()+ geom_errorbar(aes(ymin=mean_avg_pi_syn - sem_avg_pi_syn, ymax=mean_avg_pi_syn + sem_avg_pi_syn), width=.2, position=position_dodge(.9))+ ggtitle("c") +labs(y = expression(pi[s]))+ theme_classic() + theme(text = element_text(size = 10),axis.title.x=element_blank())

p5_2 <- ggplot(data = pi_genes_c_real, mapping = aes(x=category, y=mean_avg_pi_nonsyn)) + 
    geom_point()+ geom_errorbar(aes(ymin=mean_avg_pi_nonsyn - sem_avg_pi_nonsyn, ymax=mean_avg_pi_nonsyn + sem_avg_pi_nonsyn), width=.2, position=position_dodge(.9))+ ggtitle("d") +labs(y = expression(pi[n]))+ theme_classic() + theme(text = element_text(size = 10),axis.title.x=element_blank())

p4_2 + p5_2
```

# rumex
## gene sets
```{r}
directory="/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_haploid_sel/deseq2/"
genesl <- read.table(paste0(directory,"genesl.txt"), header = T)
genesp <- read.table(paste0(directory,"genesp.txt"), header = T)
unbias <- read.table(paste0(directory,"unbias.txt"), header = T)
```

## stats
```{r}
directory="/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_haploid_sel/pixy/"
statsr <- read.csv(paste0(directory,"rumex_pi_n_pi_s.csv"))

genesl <- genesl %>% dplyr::select(1)
genesp <- genesp %>% dplyr::select(1)
unbias <- unbias %>% dplyr::select(1)
statsr_genesl <- inner_join(genesl, statsr, by="gene") # 1149
statsr_genesp <- inner_join(genesp, statsr, by="gene") # 920
statsr_unbias <- inner_join(unbias, statsr, by="gene") # 615
```

## bootstrap mean & CI
```{r}
pi_genesp <- bootstrap_calculate_pi(statsr_genesp)
pi_genesp$category <- "gametophyte" 
    
pi_genesl <- bootstrap_calculate_pi(statsr_genesl)
pi_genesl$category <- "sporophyte" 

pi_unbias <- bootstrap_calculate_pi(statsr_unbias)
pi_unbias$category <- "unbiased" 

pi_genes_r <- rbind(pi_genesp, pi_genesl, pi_unbias)
directory="/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_haploid_sel/pixy/"
write.table(pi_genes_r, file = paste0(directory,"specific_genes_pi_apr.txt"), row.names = FALSE, sep = "\t", quote = FALSE)

pi_genes_r$category <- factor(pi_genes_r$category)
levels(pi_genes_r$category)
pi_genes_r$category <- factor(pi_genes_r$category,
                       levels = c("sporophyte", "unbiased","gametophyte"))

```


## plot bs mean & CI
```{r}
p1 <- ggplot(data = pi_genes_r, mapping = aes(x=category, y=mean_pi_syn)) + 
    geom_point()+ geom_errorbar(aes(ymin=lower_pi_syn, ymax=higher_pi_syn), width=.2, position=position_dodge(.9))+ ggtitle("a") +labs(y = expression(pi[s]))+ theme_classic() + theme(text = element_text(size = 10),axis.title.x=element_blank())

p2 <- ggplot(data = pi_genes_r, mapping = aes(x=category, y=mean_pi_nonsyn)) + 
    geom_point()+ geom_errorbar(aes(ymin=lower_pi_nonsyn, ymax=higher_pi_nonsyn), width=.2, position=position_dodge(.9))+ ggtitle("b") +labs(y = expression(pi[n]))+ theme_classic() + theme(text = element_text(size = 10),axis.title.x=element_blank())

p3 <- ggplot(data = pi_genes_r, mapping = aes(x=category, y=mean_ratio_pis)) + 
    geom_point()+ geom_errorbar(aes(ymin=lower_ratio_pis, ymax=higher_ratio_pis), width=.2, position=position_dodge(.9))+ ggtitle("c") +labs(y = expression(paste(pi[n], "/", pi[s], " ratio")))+ theme_classic() + theme(text = element_text(size = 10),axis.title.x=element_blank())

p1 + p2 + p3
```

```{r}
(p1 | p4) / (p2 | p5) / (p3 | p6)
```

## mean & sem
```{r}
pi_genesp <- calculate_pi_real(statsr_genesp)
pi_genesp$category <- "gametophyte" 
    
pi_genesl <- calculate_pi_real(statsr_genesl)
pi_genesl$category <- "sporophyte" 

pi_unbias <- calculate_pi_real(statsr_unbias)
pi_unbias$category <- "unbiased" 

pi_genes_r_real <- rbind(pi_genesp, pi_genesl, pi_unbias)
directory="/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_haploid_sel/pixy/"
write.table(pi_genes_r_real, file = paste0(directory,"specific_genes_pi_real.txt"), row.names = FALSE, sep = "\t", quote = FALSE)

pi_genes_r_real$category <- factor(pi_genes_r_real$category)
levels(pi_genes_r_real$category) 
pi_genes_r_real$category <- factor(pi_genes_r_real$category,
                       levels = c("sporophyte", "unbiased","gametophyte"))
```

plot mean & sem
```{r}
p1_2 <- ggplot(data = pi_genes_r_real, mapping = aes(x=category, y=mean_avg_pi_syn)) + 
    geom_point()+ geom_errorbar(aes(ymin=mean_avg_pi_syn - sem_avg_pi_syn, ymax=mean_avg_pi_syn + sem_avg_pi_syn), width=.2, position=position_dodge(.9))+ ggtitle("a") +labs(y = expression(pi[s]))+ theme_classic() + theme(text = element_text(size = 10),axis.title.x=element_blank())

p2_2 <- ggplot(data = pi_genes_r_real, mapping = aes(x=category, y=mean_avg_pi_nonsyn)) + 
    geom_point()+ geom_errorbar(aes(ymin=mean_avg_pi_nonsyn - sem_avg_pi_nonsyn, ymax=mean_avg_pi_nonsyn + sem_avg_pi_nonsyn), width=.2, position=position_dodge(.9))+ ggtitle("b") +labs(y = expression(pi[n]))+ theme_classic() + theme(text = element_text(size = 10),axis.title.x=element_blank())

p1_2 + p2_2
```


```{r}
(p1 | p1_2) / (p2 | p2_2) / (p4 | p4_2) / (p5 | p5_2) 
```

new figure s?
p3 p6 place holder
```{r}
(p1_2 | p4_2) / (p2_2 | p5_2) / (p3 | p6)
```

