---
title: "balsel scan in parallel"
author: "Meng"
date: "2023-07-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# library(GenomicRanges)
library(dplyr)
library(ggplot2)
library(patchwork)
```


```{r}
ggplot(scan1, aes(x = physPos/1000000, y = CLR))+geom_point(aes(colour=log10(s_hat)),size = 0.3)+ 
    xlab("Position on Chromosome (Mb)")+ylab("Composite Likelihood Ratio")+theme_bw() +scale_color_gradient2(name = expression('log'[10]~hat(italic(a))), limits = c(-3, 9), midpoint = 0, high="red", mid = 'white', low="blue")+ggtitle("Rumex")
```

```{r}
scanr <- read.table("rumex_scan_DAF_May9.txt",header = T)
scanr1 <-scan1[1:534110,]

p5 <- ggplot(scanr, aes(x = physPos/1000000, y = CLR))+geom_point(aes(colour=log10(s_hat)),size = 0.3)+ 
    xlab("Position on Chromosome (Mb)")+ylab("CLR")+theme_bw() +scale_color_gradient2(name = expression('log'[10]~hat(italic(a))), limits = c(-3, 9), midpoint = 0, high="red", mid = 'white', low="blue")+ggtitle("Rumex - whole genome, balancing sel + positive sel")

p6 <- ggplot(scanr1, aes(x = physPos/1000000, y = CLR))+geom_point(aes(colour=log10(s_hat)),size = 0.3)+ 
    xlab("Position on Chromosome (Mb)")+ylab("CLR")+theme_bw() +scale_color_gradient2(name = expression('log'[10]~hat(italic(a))), limits = c(-3, 9), midpoint = 0, high="red", mid = 'white', low="blue")+ggtitle("Rumex - A1 only, balancing sel only")

p5 / p6 + plot_layout(guides = "collect") & theme(legend.position = "right")
```



ceratodon_input_DAF_chrom_real.txt
ceratodon_scan_DAF_real.txt
```{r}
inputc <- read.table("ceratodon_input_DAF_chrom_real.txt",header = T)
scanc <- read.table("ceratodon_scan_DAF_real.txt",header = T)
scanc <- cbind(scanc, inputc)
scanc <- scanc[,1:8]

ggplot(scanc, aes(x = physPos/1000000, y = CLR))+geom_point(aes(colour=log10(s_hat)),size = 0.3)+
    facet_grid(.~chrom,scales="free_x", switch = "x", space = "free_x") + 
    xlab("Position on Chromosome (Mb)")+ylab("Composite Likelihood Ratio")+theme_bw() + scale_color_gradient2(name = expression('log'[10]~hat(italic(a))), limits = c(-3, 9), midpoint = 0, high="red", mid = 'white', low="blue") + ggtitle("Ceratodon")
```

