---
title: "expression level and pi plots"
author: "Meng"
date: "2024-02-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
directory="/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_haploid_sel/pixy/"
statsr <- read.csv(paste0(directory,"rumex_pi_n_pi_s.csv"))
```

## linear model
stats
statsr
```{r}
modelr <- lm(avg_pi ~ log2FoldChange + baseMean, data = stats)
summary(modelr)

modelr <- lm(avg_pi ~ abs(log2FoldChange) + baseMean, data = stats)
summary(modelr)
```

p_qt1 <- genesp %>% filter(baseMean <= 20)
p_qt2 <- genesp %>% filter(baseMean > 20 & baseMean <= 70.4)
p_qt3 <- genesp %>% filter(baseMean > 70.4 & baseMean <= 217)
p_qt4 <- genesp %>% filter(baseMean > 217)

```{r}
statsr_qt1 <- statsr %>% filter(baseMean <= 20)
statsr_qt2 <- statsr %>% filter(baseMean > 20 & baseMean <= 70.4)
statsr_qt3 <- statsr %>% filter(baseMean > 70.4 & baseMean <= 217)
statsr_qt4 <- statsr %>% filter(baseMean > 217)

# table(statsr_qt1$tag)
unique_tags <- unique(statsr$tag) # already unique

pi_r_qt1 <- data.frame(
            mean_pi_syn = numeric(),
            mean_pi_nonsyn = numeric(),
            mean_ratio_pis = numeric(),
            lower_pi_syn = numeric(),
            higher_pi_syn = numeric(),
            lower_pi_nonsyn = numeric(),
            higher_pi_nonsyn = numeric(),
            lower_ratio_pis = numeric(),
            higher_ratio_pis = numeric()
    )
for (tag in unique_tags) {
    subset_data <- statsr_qt1[statsr_qt1$tag == tag, ]
    pi_data <- bootstrap_calculate_pi(subset_data)
    pi_data$tag <- tag
    
    if (nrow(pi_r_qt1) == 0) {
        pi_r_qt1 <- pi_data
      } else {
        pi_r_qt1 <- rbind(pi_r_qt1 , pi_data)}
}

pi_r_qt2 <- data.frame(
            mean_pi_syn = numeric(),
            mean_pi_nonsyn = numeric(),
            mean_ratio_pis = numeric(),
            lower_pi_syn = numeric(),
            higher_pi_syn = numeric(),
            lower_pi_nonsyn = numeric(),
            higher_pi_nonsyn = numeric(),
            lower_ratio_pis = numeric(),
            higher_ratio_pis = numeric()
    )
for (tag in unique_tags) {
    subset_data <- statsr_qt2[statsr_qt2$tag == tag, ]
    pi_data <- bootstrap_calculate_pi(subset_data)
    pi_data$tag <- tag
    
    if (nrow(pi_r_qt2) == 0) {
        pi_r_qt2 <- pi_data
      } else {
        pi_r_qt2 <- rbind(pi_r_qt2 , pi_data)}
}

pi_r_qt3 <- data.frame(
            mean_pi_syn = numeric(),
            mean_pi_nonsyn = numeric(),
            mean_ratio_pis = numeric(),
            lower_pi_syn = numeric(),
            higher_pi_syn = numeric(),
            lower_pi_nonsyn = numeric(),
            higher_pi_nonsyn = numeric(),
            lower_ratio_pis = numeric(),
            higher_ratio_pis = numeric()
    )
for (tag in unique_tags) {
    subset_data <- statsr_qt3[statsr_qt3$tag == tag, ]
    pi_data <- bootstrap_calculate_pi(subset_data)
    pi_data$tag <- tag
    
    if (nrow(pi_r_qt3) == 0) {
        pi_r_qt3 <- pi_data
      } else {
        pi_r_qt3 <- rbind(pi_r_qt3 , pi_data)}
}

pi_r_qt4 <- data.frame(
            mean_pi_syn = numeric(),
            mean_pi_nonsyn = numeric(),
            mean_ratio_pis = numeric(),
            lower_pi_syn = numeric(),
            higher_pi_syn = numeric(),
            lower_pi_nonsyn = numeric(),
            higher_pi_nonsyn = numeric(),
            lower_ratio_pis = numeric(),
            higher_ratio_pis = numeric()
    )
for (tag in unique_tags) {
    subset_data <- statsr_qt4[statsr_qt4$tag == tag, ]
    pi_data <- bootstrap_calculate_pi(subset_data)
    pi_data$tag <- tag
    
    if (nrow(pi_r_qt4) == 0) {
        pi_r_qt4 <- pi_data
      } else {
        pi_r_qt4 <- rbind(pi_r_qt4 , pi_data)}
}

```
(-1.27,0) (-2.16,-1.27] (-3.02,-2.16]      (,-3.02]      (0,1.02]   (1.02,2.54] 
          343           315           228           211           211           185 
  (2.54,5.36]       (5.36,) 
          226           234 

```{r}
tags <- c("(,-3.02]","(-3.02,-2.16]", "(-2.16,-1.27]", "(-1.27,0)", "(0,1.02]", "(1.02,2.54]","(2.54,5.36]", "(5.36,)")
pi_r_qt1$tag <- factor(pi_r_qt1$tag,
                       levels = tags,
                       ordered = FALSE)
pi_r_qt2$tag <- factor(pi_r_qt2$tag,
                       levels = tags,
                       ordered = FALSE)
pi_r_qt3$tag <- factor(pi_r_qt3$tag,
                       levels = tags,
                       ordered = FALSE)
pi_r_qt4$tag <- factor(pi_r_qt4$tag,
                       levels = tags,
                       ordered = FALSE)

p1_1 <- ggplot(data = pi_r_qt1, mapping = aes(x=tag, y=mean_pi_syn)) + 
    geom_point()+ geom_errorbar(aes(ymin=lower_pi_syn, ymax=higher_pi_syn), width=.2, position=position_dodge(.9))+ ggtitle("a") +labs(x ="qt1",y = expression(pi[s]))+ theme_classic() + theme(text = element_text(size = 10), axis.text.x=element_blank(), axis.ticks.x=element_blank())

p2_1 <- ggplot(data = pi_r_qt1, mapping = aes(x=tag, y=mean_pi_nonsyn)) + 
    geom_point()+ geom_errorbar(aes(ymin=lower_pi_nonsyn, ymax=higher_pi_nonsyn), width=.2, position=position_dodge(.9))+ ggtitle("b") +labs(x ="qt1",y = expression(pi[n]))+ theme_classic() + theme(text = element_text(size = 10), axis.text.x=element_blank(), axis.ticks.x=element_blank())

p3_1 <- ggplot(data = pi_r_qt1, mapping = aes(x=tag, y=mean_ratio_pis)) + 
    geom_point()+ geom_errorbar(aes(ymin=lower_ratio_pis, ymax=higher_ratio_pis), width=.2, position=position_dodge(.9))+ ggtitle("c") +labs(x ="qt1",y = expression(paste(pi[n], "/", pi[s], " ratio")))+ theme_classic() + theme(text = element_text(size = 10), axis.text.x=element_blank(), axis.ticks.x=element_blank())

p1_2 <- ggplot(data = pi_r_qt2, mapping = aes(x=tag, y=mean_pi_syn)) + 
    geom_point()+ geom_errorbar(aes(ymin=lower_pi_syn, ymax=higher_pi_syn), width=.2, position=position_dodge(.9))+ ggtitle("") +labs(x ="qt2",y = expression(pi[s]))+ theme_classic() + theme(text = element_text(size = 10), axis.text.x=element_blank(), axis.ticks.x=element_blank())

p2_2 <- ggplot(data = pi_r_qt2, mapping = aes(x=tag, y=mean_pi_nonsyn)) + 
    geom_point()+ geom_errorbar(aes(ymin=lower_pi_nonsyn, ymax=higher_pi_nonsyn), width=.2, position=position_dodge(.9))+ ggtitle("") +labs(x ="qt2",y = expression(pi[n]))+ theme_classic() + theme(text = element_text(size = 10), axis.text.x=element_blank(), axis.ticks.x=element_blank())

p3_2 <- ggplot(data = pi_r_qt2, mapping = aes(x=tag, y=mean_ratio_pis)) + 
    geom_point()+ geom_errorbar(aes(ymin=lower_ratio_pis, ymax=higher_ratio_pis), width=.2, position=position_dodge(.9))+ ggtitle("") +labs(x ="qt2",y = expression(paste(pi[n], "/", pi[s], " ratio")))+ theme_classic() + theme(text = element_text(size = 10), axis.text.x=element_blank(), axis.ticks.x=element_blank())

p1_3 <- ggplot(data = pi_r_qt3, mapping = aes(x=tag, y=mean_pi_syn)) + 
    geom_point()+ geom_errorbar(aes(ymin=lower_pi_syn, ymax=higher_pi_syn), width=.2, position=position_dodge(.9))+ ggtitle("") +labs(x ="qt3",y = expression(pi[s]))+ theme_classic() + theme(text = element_text(size = 10), axis.text.x=element_blank(), axis.ticks.x=element_blank())

p2_3 <- ggplot(data = pi_r_qt3, mapping = aes(x=tag, y=mean_pi_nonsyn)) + 
    geom_point()+ geom_errorbar(aes(ymin=lower_pi_nonsyn, ymax=higher_pi_nonsyn), width=.2, position=position_dodge(.9))+ ggtitle("") +labs(x ="qt3",y = expression(pi[n]))+ theme_classic() + theme(text = element_text(size = 10), axis.text.x=element_blank(), axis.ticks.x=element_blank())

p3_3 <- ggplot(data = pi_r_qt3, mapping = aes(x=tag, y=mean_ratio_pis)) + 
    geom_point()+ geom_errorbar(aes(ymin=lower_ratio_pis, ymax=higher_ratio_pis), width=.2, position=position_dodge(.9))+ ggtitle("") +labs(x ="qt3",y = expression(paste(pi[n], "/", pi[s], " ratio")))+ theme_classic() + theme(text = element_text(size = 10), axis.text.x=element_blank(), axis.ticks.x=element_blank())


p1_4 <- ggplot(data = pi_r_qt4, mapping = aes(x=tag, y=mean_pi_syn)) + 
    geom_point()+ geom_errorbar(aes(ymin=lower_pi_syn, ymax=higher_pi_syn), width=.2, position=position_dodge(.9))+ ggtitle("") +labs(x ="qt4",y =expression(pi[s]))+ theme_classic() + theme(text = element_text(size = 10), axis.text.x=element_blank(), axis.ticks.x=element_blank())

p2_4 <- ggplot(data = pi_r_qt4, mapping = aes(x=tag, y=mean_pi_nonsyn)) + 
    geom_point()+ geom_errorbar(aes(ymin=lower_pi_nonsyn, ymax=higher_pi_nonsyn), width=.2, position=position_dodge(.9))+ ggtitle("") +labs(x ="qt4",y = expression(pi[n]))+ theme_classic() + theme(text = element_text(size = 10), axis.text.x=element_blank(), axis.ticks.x=element_blank())

p3_4 <- ggplot(data = pi_r_qt4, mapping = aes(x=tag, y=mean_ratio_pis)) + 
    geom_point()+ geom_errorbar(aes(ymin=lower_ratio_pis, ymax=higher_ratio_pis), width=.2, position=position_dodge(.9))+ ggtitle("") +labs(x ="qt4",y = expression(paste(pi[n], "/", pi[s], " ratio")))+ theme_classic() + theme(text = element_text(size = 10), axis.text.x=element_blank(), axis.ticks.x=element_blank())

(p1_1 | p1_2 | p1_3 | p1_4) / (p2_1 | p2_2 | p2_3 | p2_4) / (p3_1 | p3_2 | p3_3 | p3_4) + plot_layout(guides = "collect") 
```

save the output
```{r}
directory="/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_haploid_sel/pixy/"
write.table(pi_r_qt1, file = paste0(directory, "pi_r_qt1"), sep = "\t",row.names = FALSE, quote = FALSE)
write.table(pi_r_qt2, file = paste0(directory, "pi_r_qt2"), sep = "\t",row.names = FALSE, quote = FALSE)
write.table(pi_r_qt3, file = paste0(directory, "pi_r_qt3"), sep = "\t",row.names = FALSE, quote = FALSE)
write.table(pi_r_qt4, file = paste0(directory, "pi_r_qt4"), sep = "\t",row.names = FALSE, quote = FALSE)

pi_r_qt1 <- read.table(paste0(directory, "pi_r_qt1"), header = T)
pi_r_qt2 <- read.table(paste0(directory, "pi_r_qt2"), header = T)
pi_r_qt3 <- read.table(paste0(directory, "pi_r_qt3"), header = T)
pi_r_qt4 <- read.table(paste0(directory, "pi_r_qt4"), header = T)
```

## expression level (4 quantiles) - pi, for g- and s-biased genes

```{r}
calculate_pi_real <- function(data) {
    data <- data %>%
      mutate(pi_syn = avg_pi * no_sites.x) %>%
      mutate(pi_nonsyn = avg_pi_nonsyn * no_sites.y) #%>%
      #mutate(ratio_pis = avg_pi_nonsyn / avg_pi) # issue with division by zero
    sum_pi_syn <- sum(data$pi_syn)
    sum_pi_nonsyn <- sum(data$pi_nonsyn)
    sum_no_sites_x <- sum(data$no_sites.x)
    sum_no_sites_y <- sum(data$no_sites.y)
    
    weighted_pi_syn <- sum_pi_syn / sum_no_sites_x
    weighted_pi_nonsyn <- sum_pi_nonsyn / sum_no_sites_y
    ratio_weighted_pis <- weighted_pi_nonsyn / weighted_pi_syn
    
    mean_avg_pi_syn <- mean(data$avg_pi)
    mean_avg_pi_nonsyn <- mean(data$avg_pi_nonsyn)
    #mean_ratio_pis <- mean(data$ratio_pis)
    
    sem_avg_pi_syn <- sd(data$avg_pi) / sqrt(length(data$avg_pi))
    sem_avg_pi_nonsyn <- sd(data$avg_pi_nonsyn) / sqrt(length(data$avg_pi_nonsyn))
    #sem_ratio_pis <- sd(data$ratio_pis) / sqrt(length(data$ratio_pis))
  
    result <- data.frame(
      bias = unique(data$bias),
      expr_level = unique(data$expr_level),
      weighted_pi_syn = weighted_pi_syn,
      weighted_pi_nonsyn = weighted_pi_nonsyn,
      ratio_weighted_pis = ratio_weighted_pis,
      mean_avg_pi_syn =  mean_avg_pi_syn,
      mean_avg_pi_nonsyn = mean_avg_pi_nonsyn,
      #mean_ratio_pis = mean_ratio_pis,
      sem_avg_pi_syn = sem_avg_pi_syn,
      sem_avg_pi_nonsyn = sem_avg_pi_nonsyn
      #sem_ratio_pis = sem_ratio_pis
    )
    return(result)
}
```

```{r}
statsr <- statsr %>% mutate(expr_level = case_when(
    baseMean <= 20 ~ "qt1",
    baseMean > 20 & baseMean <= 70.4 ~ "qt2",
    baseMean > 70.4 & baseMean <= 217 ~ "qt3",
    baseMean > 217 ~ "qt4"
))

statsr <- statsr %>% mutate(bias = case_when(
    log2FoldChange > 0 ~ "g",
    log2FoldChange < 0 ~ "s"
))

# statsr_g <- statsr %>% filter(log2FoldChange > 0)
# statsr_s <- statsr %>% filter(log2FoldChange < 0)
    

grouped_data <- statsr %>%
  group_by(bias, expr_level)

results_list <- lapply(split(grouped_data, interaction(grouped_data$bias, grouped_data$expr_level)), function(group) {
  calculate_pi_real(group)
})

pi_expr_qt <- bind_rows(results_list)

```

```{r}
#expressed <- cnt %>% filter(p_mean>5 | l_mean>5) #17984
DE_tissue <- DE_tissue %>% filter(p_mean>5 | l_mean>5) #17982
bins.quantiles(DE_tissue$baseMean, 10, 10, verbose = FALSE)

statsr <- statsr %>% mutate(expr_level = case_when(
    baseMean <= 6.845 ~ "qt1",
    baseMean > 6.845 & baseMean <= 14.371 ~ "qt2",
    baseMean > 14.371 & baseMean <= 26.3 ~ "qt3",
    baseMean > 26.3 & baseMean <= 44.4 ~ "qt4",
    baseMean > 44.4 & baseMean <= 70.26 ~ "qt5",
    baseMean > 70.26 & baseMean <= 107.809 ~ "qt6",
    baseMean > 107.809 & baseMean <= 168.41 ~ "qt7",
    baseMean > 168.41 & baseMean <= 291.6 ~ "qt8",
    baseMean > 291.6 & baseMean <= 670 ~ "qt9",
    baseMean > 670 ~ "qt10"
))

table(statsr$expr_level)
grouped_data <- statsr %>%
  group_by(bias, expr_level)

results_list <- lapply(split(grouped_data, interaction(grouped_data$bias, grouped_data$expr_level)), function(group) {
  calculate_pi_real(group)
})

pi_expr_qt10 <- bind_rows(results_list)

pi_expr_qt10 <- pi_expr_qt10 %>% mutate(expr_level = factor(expr_level, levels = c("qt1", "qt2", "qt3", "qt4", "qt5", "qt6", "qt7", "qt8","qt9", "qt10")))
levels(pi_expr_qt10$expr_level)


p1 <- ggplot(data = pi_expr_qt10, mapping = aes(x=expr_level, y=weighted_pi_syn, colour = bias)) + 
    geom_point()+ ggtitle("a") +labs(x ="expression level quantiles",y = expression(pi[s]))+ theme_classic() + theme(text = element_text(size = 10)) 

p2 <- ggplot(data = pi_expr_qt10, mapping = aes(x=expr_level, y=weighted_pi_nonsyn, colour = bias)) + 
    geom_point()+ ggtitle("b") +labs(x ="expression level quantiles",y = expression(pi[n]))+ theme_classic() + theme(text = element_text(size = 10)) 

p3 <- ggplot(data = pi_expr_qt10, mapping = aes(x=expr_level, y=ratio_weighted_pis, colour = bias)) + ggtitle("c")+
    geom_point() +labs(x ="expression level quantiles",y = expression(paste(pi[n], "/", pi[s], " ratio")))+ theme_classic() + theme(text = element_text(size = 10)) 

p1 + p2 + p3+ plot_layout(nrow = 1,guides = "collect") & theme(legend.position = "right")
```
qt1 qt10  qt2  qt3  qt4  qt5  qt6  qt7  qt8  qt9 
 686 1445  785  925 1056 1231 1336 1386 1420 1464 
[0.0298937364341198, 6.84469234925497]    [6.8450746321015, 14.3702356623989] 
                                  1799                                   1798 
  [14.3713554606715, 26.2929049546056]   [26.3115769967044, 44.3988187202997] 
                                  1798                                   1798 
  [44.4441271087276, 70.2100243661586]   [70.2608560406953, 107.803948501274] 
                                  1798                                   1798 
   [107.809680647553, 168.40866407541]   [168.413962577764, 291.573892918416] 
                                  1798                                   1798 
  [291.633360932102, 668.961121141881]   [670.130779158352, 638812.291330801] 
                                  1798                                   1799

```{r}
p1 <- ggplot(data = pi_expr_qt, mapping = aes(x=expr_level, y=mean_avg_pi_syn, colour = bias)) + 
    geom_point()+ geom_errorbar(aes(ymin=mean_avg_pi_syn - sem_avg_pi_syn, ymax=mean_avg_pi_syn + sem_avg_pi_syn), width=.2)+ ggtitle("a") +labs(x ="expression level quantiles",y = expression(pi[s]))+ theme_classic() + theme(text = element_text(size = 10)) 

p2 <- ggplot(data = pi_expr_qt, mapping = aes(x=expr_level, y=mean_avg_pi_nonsyn, colour = bias)) + 
    geom_point()+ geom_errorbar(aes(ymin=mean_avg_pi_nonsyn - sem_avg_pi_nonsyn, ymax=mean_avg_pi_nonsyn + sem_avg_pi_nonsyn), width=.2)+ ggtitle("b") +labs(x ="expression level quantiles",y = expression(pi[n]))+ theme_classic() + theme(text = element_text(size = 10)) 

p1 + p2 + p1c + p2c + plot_layout(nrow = 2,guides = "collect") & theme(legend.position = "right")
```
```{r}
p3 <- ggplot(data = pi_expr_qt, mapping = aes(x=expr_level, y=weighted_pi_syn, colour = bias)) + 
    geom_point()+ ggtitle("") +labs(x ="expression level quantiles",y = expression(pi[s]))+ theme_classic() + theme(text = element_text(size = 10)) 

p4 <- ggplot(data = pi_expr_qt, mapping = aes(x=expr_level, y=weighted_pi_nonsyn, colour = bias)) + 
    geom_point()+ ggtitle("") +labs(x ="expression level quantiles",y = expression(pi[n]))+ theme_classic() + theme(text = element_text(size = 10)) 

p3 + p4 + plot_layout(nrow = 1,guides = "collect") & theme(legend.position = "right")
```
piN/piS?
```{r}
pi_expr_qt <- pi_expr_qt %>% mutate(ratio_pis = weighted_pi_nonsyn / weighted_pi_syn)

p3 <- ggplot(data = pi_expr_qt, mapping = aes(x=expr_level, y=ratio_pis, colour = bias)) + 
    geom_point()+ ggtitle("rumex") +labs(x ="expression level quantiles",y = expression(paste(pi[n], "/", pi[s], " ratio")))+ theme_classic() + theme(text = element_text(size = 10)) 

p3 + p3c + plot_layout(nrow = 1,guides = "collect") & theme(legend.position = "right")
```

```{r}
p3 <- ggplot(data = statsr, mapping = aes(x=log10(baseMean), y=avg_pi, colour = bias)) + geom_point(alpha =0.1)+ geom_smooth()+ ggtitle("a") +labs(x ="log10(baseMean)",y = expression(pi[s]))+ theme_classic() + theme(text = element_text(size = 10)) 

p4 <- ggplot(data = statsr, mapping = aes(x=log10(baseMean), y=avg_pi_nonsyn, colour = bias)) + geom_point(alpha =0.1)+ geom_smooth()+ ggtitle("b") +labs(x ="log10(baseMean)",y = expression(pi[n]))+ theme_classic() + theme(text = element_text(size = 10)) 

p3 + p4

p3 + p4 + p3c + p4c + plot_layout(nrow = 2,guides = "collect") & theme(legend.position = "right")

```

## write output
```{r}
directory="/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_haploid_sel/pixy/"
write.table(pi_expr_qt, file=paste0(directory,"pi_expr_qt_c.txt"), sep = "\t",row.names = FALSE, quote = FALSE)
write.table(statsr, file=paste0(directory,"statsr.txt"), sep = "\t",row.names = FALSE, quote = FALSE)

```



## check recombination rate for each bin

```{r}

head(statsr)
pos <- statsr[,c(1,8:9)]
write.table(pos, file = "/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_haploid_sel/pixy/pos.txt", sep = "\t",row.names = FALSE, quote = FALSE)
```

