---
title: "tajD and expr level"
author: "Meng"
date: "2024-03-28"
output: html_document
---

```{r setup, include=FALSE}
library(patchwork)
library(dplyr)
library(ggplot2)
directory="/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_haploid_sel/pixy/"
FC_tajD <- read.table(paste0(directory,"FC_tajD_innerjoin.txt"), header =T)
FC_tajD_n <- read.table(paste0(directory,"FC_tajD_nonsyn_innerjoin.txt"), header =T)
```

```{r}
get_tajD <- function(data) {
        count <- length(data$TajD_TX)
        mean_tajD <- mean(data$TajD_TX)
        sem_tajD <- sd(data$TajD_TX)/sqrt(length(data$TajD_TX))
        bias <- unique(data$bias)
        expr_level <- unique(data$expr_level)
        
        result <- data.frame(
        count = count,
        mean_tajD = mean_tajD,
        sem_tajD = sem_tajD,
        bias = bias,
        expr_level = expr_level
        )
  return(result)
}
```


## TajD syn
```{r}
FC_tajD <- FC_tajD %>% mutate(expr_level = case_when(
    baseMean <= 20 ~ "qt1",
    baseMean > 20 & baseMean <= 70.4 ~ "qt2",
    baseMean > 70.4 & baseMean <= 217 ~ "qt3",
    baseMean > 217 ~ "qt4"
))

FC_tajD <- FC_tajD %>% mutate(bias = case_when(
    log2FoldChange > 0 ~ "g",
    log2FoldChange < 0 ~ "s"
))

table(FC_tajD$expr_level)
table(FC_tajD$bias)

grouped_data <- FC_tajD %>%
  group_by(bias, expr_level)


results_list <- lapply(split(grouped_data, interaction(grouped_data$bias, grouped_data$expr_level)), function(group) {
  get_tajD(group)
})

tajD_expr_syn <- bind_rows(results_list)
```
 qt1  qt2  qt3  qt4 
1784 1876 1987 1987 
 g    s 
2920 4714 

```{r}
FC_tajD_n <- FC_tajD_n %>% mutate(expr_level = case_when(
    baseMean <= 20 ~ "qt1",
    baseMean > 20 & baseMean <= 70.4 ~ "qt2",
    baseMean > 70.4 & baseMean <= 217 ~ "qt3",
    baseMean > 217 ~ "qt4"
))

FC_tajD_n <- FC_tajD_n %>% mutate(bias = case_when(
    log2FoldChange > 0 ~ "g",
    log2FoldChange < 0 ~ "s"
))

table(FC_tajD_n$expr_level)
table(FC_tajD_n$bias)

grouped_data <- FC_tajD_n %>%
  group_by(bias, expr_level)

results_list <- lapply(split(grouped_data, interaction(grouped_data$bias, grouped_data$expr_level)), function(group) {
  get_tajD(group)
})

tajD_expr_nonsyn <- bind_rows(results_list)
```
 qt1  qt2  qt3  qt4 
3014 3146 3230 3268 
   g    s 
4979 7679 

## plots
```{r}
p1 <- ggplot(data = tajD_expr_syn, mapping = aes(x=expr_level, y=mean_tajD, colour = bias)) + 
    geom_point(position=position_dodge(.9))+ geom_errorbar(aes(ymin=mean_tajD - sem_tajD, ymax=mean_tajD + sem_tajD), width=.2, position=position_dodge(.9))+ ggtitle("a") +labs(x ="expression level quantiles",y = expression(D[s]))+ theme_classic() + theme(text = element_text(size = 10)) 

p2 <- ggplot(data = tajD_expr_nonsyn, mapping = aes(x=expr_level, y=mean_tajD, colour = bias)) + 
    geom_point(position=position_dodge(.9))+ geom_errorbar(aes(ymin=mean_tajD - sem_tajD, ymax=mean_tajD + sem_tajD), width=.2, position=position_dodge(.9))+ ggtitle("b") +labs(x ="expression level quantiles",y = expression(D[n]))+ theme_classic() + theme(text = element_text(size = 10)) 

p1 + p2 + p1c + p2c + plot_layout(nrow = 2,guides = "collect") & theme(legend.position = "right")

```



```{r}
p3 <- ggplot(data = FC_tajD, mapping = aes(x=baseMean, y=TajD_TX, colour = bias)) + geom_point()+ geom_smooth()+ ggtitle("a") +labs(x ="expression level",y = expression(D[s]))+ theme_classic() + theme(text = element_text(size = 10)) + xlim(0,10000)

p4 <- ggplot(data = FC_tajD_n, mapping = aes(x=baseMean, y=TajD_TX, colour = bias)) + geom_point()+ geom_smooth()+ ggtitle("b") +labs(x ="expression level",y = expression(D[n]))+ theme_classic() + theme(text = element_text(size = 10)) + xlim(0,10000)

#p3 + p4

p3 + p4 + p3c + p4c + plot_layout(nrow = 2,guides = "collect") & theme(legend.position = "right")

```

