---
title: "FC diversity and bootstrapping in rumex"
author: "Meng"
date: "2023-12-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(patchwork)
directory="/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_haploid_sel/pixy/"
```

## merge pi estimates
```{r}
FC_pixy <- read.table(paste0(directory,"FC_pixy_innerjoin.txt"),header = TRUE) #11734
pixy_nonsyn <- read.table(paste0(directory,"pixy_pi_nonsyn.0329.genewise.txt"), header=TRUE) #27026
colnames(pixy_nonsyn)[2:5] <- c("chrom", "start", "end", "avg_pi_nonsyn")
pixy_nonsyn <- pixy_nonsyn %>% filter(no_sites>=50) # 22186

statsr <- inner_join(FC_pixy, pixy_nonsyn, by=c("pop", "chrom", "start", "end")) # 11734
write.csv(statsr, file = paste0(directory,"rumex_pi_n_pi_s.csv"), row.names = FALSE, quote = FALSE)
```

## weighted average pi_s within each bin
add pi_n and pi_n / pi_s next
```{r}
statsr <- read.csv(paste0(directory,"rumex_pi_n_pi_s.csv"))

tags <- c("(,-3.02]","(-3.02,-2.16]", "(-2.16,-1.27]", "(-1.27,0)", "(0,1.02]", "(1.02,2.54]","(2.54,5.36]", "(5.36,)")

statsr <- as_tibble(statsr) %>% 
  mutate(tag = case_when(
    log2FoldChange > 0 & log2FoldChange <= 1.02 ~ tags[5],
    log2FoldChange > 1.02 & log2FoldChange <= 2.54 ~ tags[6],
    log2FoldChange > 2.54 & log2FoldChange <= 5.36 ~ tags[7],
    log2FoldChange > 5.36   ~ tags[8],
    
    log2FoldChange <= -3.02 ~ tags[1],
    log2FoldChange > -3.02 & log2FoldChange <= -2.16 ~ tags[2],
    log2FoldChange > -2.16 & log2FoldChange <= -1.27 ~ tags[3],
    log2FoldChange > -1.27 & log2FoldChange < 0 ~ tags[4]
    ))
table(statsr$tag)
```

## function to do bootstraps and get pi_n pi_s and the ratio
```{r}
# a function to calculate the weighted average of pi_n pi_s
calculate_pi <- function(data) {
    data <- data %>%
      mutate(pi_syn = avg_pi * no_sites.x) %>%
      mutate(pi_nonsyn = avg_pi_nonsyn * no_sites.y)
    sum_pi_syn <- sum(data$pi_syn)
    sum_pi_nonsyn <- sum(data$pi_nonsyn)
    sum_no_sites_x <- sum(data$no_sites.x)
    sum_no_sites_y <- sum(data$no_sites.y)
    weighted_pi_syn <- sum_pi_syn / sum_no_sites_x
    weighted_pi_nonsyn <- sum_pi_nonsyn / sum_no_sites_y
    ratio_weighted_pis <- weighted_pi_nonsyn / weighted_pi_syn
    result <- data.frame(
      weighted_pi_syn = weighted_pi_syn,
      weighted_pi_nonsyn = weighted_pi_nonsyn,
      ratio_weighted_pis = ratio_weighted_pis
    )
    return(result)
  }
  
# bootstrap and calculate the mean and 95% of weighted average of pi_n pi_s pi_n/pi_s
bootstrap_calculate_pi <- function(data, iterations = 1000) {
    # set up the output format
    results <- data.frame(weighted_pi_syn = numeric(), weighted_pi_nonsyn = numeric(),   ratio_weighted_pis = numeric(), stringsAsFactors = FALSE)
    
    # bootstrap 1000 times and save to result
    for (i in 1:iterations) {
      resampled_data <- data[sample(nrow(data), replace = TRUE), ]
      calculated_values <- calculate_pi(resampled_data)
      if (nrow(results) == 0) {
        results <- calculated_values
      } else {
        results <- rbind(results, calculated_values)}
    }

    # calculate the mean and 95% CI from bootstrapped values
    output <- data.frame(
            mean_pi_syn = mean(results$weighted_pi_syn),
            mean_pi_nonsyn = mean(results$weighted_pi_nonsyn),
            mean_ratio_pis = mean(results$ratio_weighted_pis),
            lower_pi_syn = quantile(results$weighted_pi_syn, 0.025),
            higher_pi_syn = quantile(results$weighted_pi_syn, 0.975),
            lower_pi_nonsyn = quantile(results$weighted_pi_nonsyn, 0.025),
            higher_pi_nonsyn = quantile(results$weighted_pi_nonsyn, 0.975),
            lower_ratio_pis = quantile(results$ratio_weighted_pis, 0.025),
            higher_ratio_pis = quantile(results$ratio_weighted_pis, 0.975)
    )
    return(output)
  }
  
# test the functions
test_data <- statsr[statsr$tag == "(-3.02,-2.16]", ]
pi_r <- calculate_pi(test_data)
pi_r <- bootstrap_calculate_pi(test_data)
pi_r$tag <- "(-3.02,-2.16]"

# real data
pi_r <- data.frame(
            mean_pi_syn = numeric(),
            mean_pi_nonsyn = numeric(),
            mean_ratio_pis = numeric(),
            lower_pi_syn = numeric(),
            higher_pi_syn = numeric(),
            lower_pi_nonsyn = numeric(),
            higher_pi_nonsyn = numeric(),
            lower_ratio_pis = numeric(),
            higher_ratio_pis = numeric()
    )

unique_tags <- unique(statsr$tag) # already unique
for (tag in unique_tags) {
    subset_data <- statsr[statsr$tag == tag, ]
    pi_data <- bootstrap_calculate_pi(subset_data)
    pi_data$tag <- tag
    
    if (nrow(pi_r) == 0) {
        pi_r <- pi_data
      } else {
        pi_r <- rbind(pi_r, pi_data)}
}
# save the output
directory="/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_haploid_sel/pixy/"
write.table(pi_r, file=paste0(directory,"pi_weighted_mean_CI.txt"), sep = "\t",row.names = FALSE, quote = FALSE)

tag_cnt <- group_by(statsr, tag) %>%
  dplyr::summarise(
    count = n()
  )
pi_r <- left_join(pi_r, tag_cnt, by = "tag")
pi_r <- pi_r[,c(10:11,c(1:9))]
```


## plot the output
```{r}
tags <- c("(,-3.02]","(-3.02,-2.16]", "(-2.16,-1.27]", "(-1.27,0)", "(0,1.02]", "(1.02,2.54]","(2.54,5.36]", "(5.36,)")
pi_r$tag <- factor(pi_r$tag,
                       levels = tags,
                       ordered = FALSE)

p1 <- ggplot(data = pi_r, mapping = aes(x=tag, y=mean_pi_syn)) + 
    geom_point()+ geom_errorbar(aes(ymin=lower_pi_syn, ymax=higher_pi_syn), width=.2, position=position_dodge(.9))+ ggtitle("a") +labs(x ="log2FoldChange",y ="pi_syn")+ theme_classic() + theme(text = element_text(size = 10), axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank())

p2 <- ggplot(data = pi_r, mapping = aes(x=tag, y=mean_pi_nonsyn)) + 
    geom_point()+ geom_errorbar(aes(ymin=lower_pi_nonsyn, ymax=higher_pi_nonsyn), width=.2, position=position_dodge(.9))+ ggtitle("b") +labs(x ="log2FoldChange",y ="pi_nonsyn")+ theme_classic() + theme(text = element_text(size = 10), axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank())

p3 <- ggplot(data = pi_r, mapping = aes(x=tag, y=mean_ratio_pis)) + 
    geom_point()+ geom_errorbar(aes(ymin=lower_ratio_pis, ymax=higher_ratio_pis), width=.2, position=position_dodge(.9))+ ggtitle("c") +labs(x ="log2FoldChange",y ="pi_n / pi_s")+ theme_classic() + theme(text = element_text(size = 10), axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank())

p1 + p2 + p3 + plot_layout(nrow = 3,guides = "collect") 
```


