featureCounts -F GTF -p -T 10 -t mRNA -g Parent -a /ohta2/meng.yuan/ceratodon/genome/R40_GG1U_combined.gff -o /ohta2/meng.yuan/ceratodon/featureCount/readcnts_ceratodon_mRNA_gene_g.txt \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268976_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268977_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268978_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268979_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268980_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268981_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268982_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268983_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268984_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268985_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268986_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268987_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268988_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268989_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268990_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268991_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268992_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268993_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268994_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268995_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268996_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268997_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268998_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8268999_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8269000_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8269001_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8269002_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8269003_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8269004_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8269005_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8269006_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8269007_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8269008_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8269009_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8269010_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_gRNA_2genomes/AnalysisReady_SRR8269011_f.bam \
>> g_2genome.out 2>&1
