
featureCounts -F GTF -p -T 20 -t mRNA -g Parent -a /ohta2/meng.yuan/ceratodon/genome/R40_GG1U_combined.gff -o /ohta2/meng.yuan/ceratodon/featureCount/readcnts_ceratodon_mRNA_gene_s_f.txt \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDBM_RNAseq_B150_B190_G_2_Plate1_GGACTTGG_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDBN_RNAseq_B150_B190_G_3_Plate1_AAGTCCAA_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDBP_RNAseq_B150_B190_G_4_Plate1_ATCCACTG_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDBQ_RNAseq_B150_B190_G_5_Plate1_GCTTGTCA_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDBR_RNAseq_B150_B190_G_6_Plate1_CAAGCTAG_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDBT_RNAseq_B150_O110_G_1_Plate1_AGTTCAGG_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDBU_RNAseq_B150_O110_G_2_Plate1_GACCTGAA_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDBW_RNAseq_B150_O110_G_3_Plate1_TCTCTACT_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDBX_RNAseq_B150_O110_G_4_Plate1_CTCTCGTC_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDBY_RNAseq_B150_O110_G_5_Plate1_CCAAGTCT_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDBZ_RNAseq_B150_O110_G_6_Plate1_TTGGACTC_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDCA_RNAseq_B150_O110_G_7_Plate1_GGCTTAAG_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDCB_RNAseq_B150_O110_G_8_Plate1_AATCCGGA_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDCC_RNAseq_B150_O110_G_9_Plate1_TAATACAG_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDCD_RNAseq_B150_O110_G_10_Plate1_CGGCGTGA_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDCE_RNAseq_G150_B190_G_1_Plate1_ATGTAAGT_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDCF_RNAseq_G150_B190_G_2_Plate1_GCACGGAC_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDCG_RNAseq_G150_B190_G_3_Plate1_GGTACCTT_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDCH_RNAseq_G150_G100_G_1_Plate1_AACGTTCC_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDCI_RNAseq_G150_G100_G_2_Plate1_GCAGAATT_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDCJ_RNAseq_G150_O110_G_1_Plate1_ATGAGGCC_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDCK_RNAseq_G150_O110_G_2_Plate1_ACTAAGAT_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDCL_RNAseq_G150_O110_G_3_Plate1_GTCGGAGC_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDCM_RNAseq_L120_O110_G_1_Plate1_CTTGGTAT_Ceratodon_purpureus_I1044_L3_f.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_F/AnalysisReady_JDCN_RNAseq_L120_O110_G_2_Plate1_TCCAACGC_Ceratodon_purpureus_I1044_L3_f.bam 



featureCounts -F GTF -p -T 20 -t mRNA -g Parent -a /ohta2/meng.yuan/ceratodon/genome/R40_GG1U_combined.gff -o /ohta2/meng.yuan/ceratodon/featureCount/readcnts_ceratodon_mRNA_gene_s_m.txt \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDBM_RNAseq_B150_B190_G_2_Plate1_GGACTTGG_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDBN_RNAseq_B150_B190_G_3_Plate1_AAGTCCAA_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDBP_RNAseq_B150_B190_G_4_Plate1_ATCCACTG_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDBQ_RNAseq_B150_B190_G_5_Plate1_GCTTGTCA_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDBR_RNAseq_B150_B190_G_6_Plate1_CAAGCTAG_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDBT_RNAseq_B150_O110_G_1_Plate1_AGTTCAGG_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDBU_RNAseq_B150_O110_G_2_Plate1_GACCTGAA_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDBW_RNAseq_B150_O110_G_3_Plate1_TCTCTACT_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDBX_RNAseq_B150_O110_G_4_Plate1_CTCTCGTC_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDBY_RNAseq_B150_O110_G_5_Plate1_CCAAGTCT_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDBZ_RNAseq_B150_O110_G_6_Plate1_TTGGACTC_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDCA_RNAseq_B150_O110_G_7_Plate1_GGCTTAAG_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDCB_RNAseq_B150_O110_G_8_Plate1_AATCCGGA_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDCC_RNAseq_B150_O110_G_9_Plate1_TAATACAG_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDCD_RNAseq_B150_O110_G_10_Plate1_CGGCGTGA_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDCE_RNAseq_G150_B190_G_1_Plate1_ATGTAAGT_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDCF_RNAseq_G150_B190_G_2_Plate1_GCACGGAC_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDCG_RNAseq_G150_B190_G_3_Plate1_GGTACCTT_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDCH_RNAseq_G150_G100_G_1_Plate1_AACGTTCC_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDCI_RNAseq_G150_G100_G_2_Plate1_GCAGAATT_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDCJ_RNAseq_G150_O110_G_1_Plate1_ATGAGGCC_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDCK_RNAseq_G150_O110_G_2_Plate1_ACTAAGAT_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDCL_RNAseq_G150_O110_G_3_Plate1_GTCGGAGC_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDCM_RNAseq_L120_O110_G_1_Plate1_CTTGGTAT_Ceratodon_purpureus_I1044_L3_m.bam \
/ohta2/meng.yuan/ceratodon/BAM_AnalysisReady/AnalysisReady_sRNA_M/AnalysisReady_JDCN_RNAseq_L120_O110_G_2_Plate1_TCCAACGC_Ceratodon_purpureus_I1044_L3_m.bam













