---
title: "top GO for ceratodon"
author: "Meng"
date: "2023-11-02"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(topGO)
library(stringr)
directory="/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/ceratodon_haploid_sel/deseq2/"
```

## gene to GO info
extract gene GO mapping from R40 genome
remove UV genes
keep only expressed genes

```{r}
gene2GO <- read.table(paste0(directory, "CpurpureusR40_538_v1.1.annotation_info.txt"), sep = "\t")
gene2GO <- gene2GO[, c(2,10)]
colnames(gene2GO) <- c("gene", "GO")
gene2GO <- gene2GO %>% filter(GO != "") # 20025

# CepurR40.1G023200 -> gene-KC19_10G000900
gene2GO$gene <- str_replace(gene2GO$gene, "CepurR40.", "gene-KC19_")

gff<-read.table(paste0(directory,"R40_GG1U_combined.gene.final.gff"))
colnames(gff)<-c("chrom","start","end","gene")

gene2GO <- inner_join(gene2GO, gff, by = "gene")

DE_c <- read.table("/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/ceratodon_haploid_sel/deseq2/DE_results_all.txt", header =T) # 30107
DE_c <- DE_c %>% filter(g_mean > 5 | s_mean > 5) # 25861 (including UV)
DE_c <- DE_c %>% filter(chrom != "U" & chrom != "V")
gene2GO <- inner_join(gene2GO, DE_c, by = c("gene", "chrom", "start", "end")) # 17354

write.csv(gene2GO, file = paste0(directory, "gene2GO_full.csv"))
write.table(gene2GO[,c(1,2)], file = paste0(directory, "gene2GO.txt"), sep = "\t", quote = F, row.names = F) 

gene2GO <- gene2GO %>% filter(log2FoldChange>0) # 9420
write.table(gene2GO[,c(1,2)], file = paste0(directory, "gene2GO_gbias.txt"), sep = "\t", quote = F, row.names = F) 

```


## interesting genes
```{r}
sbias <- read.table(paste0(directory, "sporo_biased_p01_FC2.txt"), header =T)
gbias <- read.table(paste0(directory, "gameto_biased_p01_FC2.txt"), header =T)

geness <- read.table(paste0(directory, "geness.txt"), header =T)
genesg <- read.table(paste0(directory, "genesg.txt"), header =T)

balsel_genes <- read.table("/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/ceratodon_haploid_sel/balsel/balsel_genes_expressed.txt", header = T)
balsel_gbias <- balsel_genes %>% filter(log2FoldChange>0 & padj < 0.1) # 334

myInterestingGenes <- genesg$gene
myInterestingGenes <- geness$gene

myInterestingGenes <- gbias$gene
myInterestingGenes <- sbias$gene

myInterestingGenes <- balsel_genes$gene
myInterestingGenes <- balsel_gbias$gene

```


```{r}
geneID2GO <- readMappings(file = paste0(directory, "gene2GO.txt"))
# for comparing g biased balsel genes
# geneID2GO <- readMappings(file = paste0(directory, "gene2GO_gbias.txt"))
str(head(geneID2GO))

# the gene universe (all the genes you have)
geneNames <- names(geneID2GO)
head(geneNames)

geneList <- factor(as.integer(geneNames %in% myInterestingGenes))
names(geneList) <- geneNames
str(geneList)

sampleGOdata <- new("topGOdata", ontology = "BP",
                     allGenes = geneList,
                     annot = annFUN.gene2GO, gene2GO = geneID2GO)

weight01.fisher <- runTest(sampleGOdata, algorithm='weight01', statistic = "fisher")
results_table = GenTable(sampleGOdata, P_value=weight01.fisher, orderBy="P_value")
```


```{r}
write.csv(results_table, file=paste0(directory, "balsel_genes_GO.csv"),row.names = FALSE, quote=FALSE )
write.csv(results_table, file=paste0(directory, "balsel_gbias_GO.csv"),row.names = FALSE, quote=FALSE )

write.csv(results_table, file=paste0(directory, "gspecific_GO.csv"),row.names = FALSE, col.names = FALSE, quote=FALSE )
write.csv(results_table, file=paste0(directory, "sspecific_GO.csv"),row.names = FALSE, col.names = FALSE, quote=FALSE )

write.csv(results_table, file=paste0(directory, "gbias_GO.csv"),row.names = FALSE, col.names = FALSE, quote=FALSE )
write.csv(results_table, file=paste0(directory, "sbias_GO.csv"),row.names = FALSE, col.names = FALSE, quote=FALSE )
```


